name: Process Java Code

on:
  push:
    paths:
      - 'input.java'

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Download Python script
        run: |
          curl -o main.py https://raw.githubusercontent.com/Buhnana/FFP-Replacer/main/main.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Create a requirements.txt file if necessary, or comment this line if no dependencies
          echo "No dependencies required" > requirements.txt
          pip install -r requirements.txt || true

      - name: Run Python script
        run: |
          python main.py

      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: updated-java-code
          path: updated_source.java
