name: Process Java Code

on:
  push:
    paths:
      - '*.java'  # Trigger on any .java file

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Download Python script
        run: |
          curl -H "Authorization: token ${{ secrets.GH_PAT }}" -o main.py https://raw.githubusercontent.com/Buhnana/FFP-Replacer/main/main.py

      - name: Verify Python script
        run: |
          cat main.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          echo "No dependencies required" > requirements.txt
          pip install -r requirements.txt || true

      - name: Run Python script
        run: |
          mkdir -p java_files
          mv *.java java_files/
          python main.py

      - name: Move processed files back
        run: |
          mv java_files/*.java ./

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: processed-java-files
          path: '*.java'
